// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtX4rtx_IX0dzp2LfoBqgMP7NwPeMcZE',
    appId: '1:1082491597632:web:dbeedbe6dd64680d0dc0a5',
    messagingSenderId: '1082491597632',
    projectId: 'ecommerce-c01da',
    authDomain: 'ecommerce-c01da.firebaseapp.com',
    storageBucket: 'ecommerce-c01da.appspot.com',
    measurementId: 'G-G628WQB946',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ifygmk6xk1KyMKPrcmUY4hXGtxPbIUY',
    appId: '1:1082491597632:android:2b234f483f98d4030dc0a5',
    messagingSenderId: '1082491597632',
    projectId: 'ecommerce-c01da',
    storageBucket: 'ecommerce-c01da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAuImc0dH1-lnx9VgTw9lLlxmF4o8R1m0',
    appId: '1:1082491597632:ios:84c5f9e186ae0f150dc0a5',
    messagingSenderId: '1082491597632',
    projectId: 'ecommerce-c01da',
    storageBucket: 'ecommerce-c01da.appspot.com',
    iosClientId: '1082491597632-7jk0dbh5vb77ddl7jlm85na8dqt8ii83.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAuImc0dH1-lnx9VgTw9lLlxmF4o8R1m0',
    appId: '1:1082491597632:ios:84c5f9e186ae0f150dc0a5',
    messagingSenderId: '1082491597632',
    projectId: 'ecommerce-c01da',
    storageBucket: 'ecommerce-c01da.appspot.com',
    iosClientId: '1082491597632-7jk0dbh5vb77ddl7jlm85na8dqt8ii83.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
